language: node_js

node_js:
  - "0.10"
script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

after_failure:
  - "curl -X GET http://127.0.0.1:5984/_log?bytes=1000000"

env:
  matrix:
  - COMMAND=test
  - COMMAND=test-firefox
#  - COMMAND=test-phantomjs # Restore when https://code.google.com/p/selenium/issues/detail?id=8088 fixed
  - COMMAND=coverage

branches:
  only:
  - master
  - /^pull*$/
